### ISSUE TITLE
New Checklist - Stuff to do

### ISSUE THREAD

**Issue by jdaly13** [jdaly13/yellow-in-green#41]
Documentation
- [ ] update Readme.md and reference folder for documentation public and private
Analytics
- [x] integrate analytics - either google analytics or mixpanel
- [ ] Update search indexing for site - https://search.google.com/search-console/index?resource_id=sc-domain%3Ayellowingreen.com - update robots.txt and create a sitemap as well.

General
- [ ] Upgrade Infura or switch to Alchemy or combo of both

Google Cloud 
- [ ] merge mysql branch into master and change cloud build to build off master branch
- [ ] Learn to create better build config files - https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration

NFT
- [ ] Learn about embedding JSON data into the NFT contract itself - https://docs.alchemy.com/docs/how-to-make-nfts-with-on-chain-metadata-hardhat-and-javascript https://medium.com/quick-programming/how-to-implement-fully-on-chain-nft-contracts-8c409acc98b7
- [ ] create a webhook possibly that when email is sent it sends NFT token

ADMIN Panel
- [ ] - Ability to either delete or update questions and answers in admin panel

Smart Contract
- [ ] Upgradeable contracts
- [x] ability to deposit and withdraw native token on Pool contract
- [ ] Move tokens to new address that not hosted on cloud - look into multi sig wallet mpcvault gnosis

Application

- [x] replacement fee - 2 transactions at once - https://github.com/ethers-io/ethers.js/issues/444 - https://github.com/ethers-io/ethers.js/issues/435
- [x] captcha on faucet

Dev Ops

- [ ] Add Cloudflare
